export const PRODUCT_FETCHED_SUCCESS = "PRODUCT_FETCHED_SUCCESS";
export const PRODUCT_FETCHED_FAILED = "PRODUCT_FETCHED_FAILED";
export const PRODUCT_FETCHED_LOADING = "PRODUCT_FETCHED_LOADING";

export const SEARCH_FETCHED_LOADING = "SEARCH_FETCHED_LOADING";
export const SEARCH_FETCHED_FAILED = "SEARCH_FETCHED_FAILED";
export const SEARCH_FETCHED_SUCCESS = "SEARCH_FETCHED_SUCCESS";